text_one = input('Введите Ваш текст: ')
print('Ваш текст: ', text_one)
text_two = input('Введите Ваш текст еще раз: ')
print('Ваш текст: ', text_two)
number_one = input('Введите Ваше число: ')
print('Ваше число: ', number_one)
number_two = input('Введите Ваше число еще раз: ')
print('Ваше число: ', number_two)
